services:
  web:
    image: odoo:${ODK_ODOO_TAG}
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ${ODK_ADDONS}:/mnt/extra-addons
    environment:
      HOST: db
      USER: odoo
      PASSWORD: pwd
    
  db:
    image: postgres:${ODK_POSTGRES_TAG}
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: pwd
      PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  # odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass